apiVersion: v1
kind: Service
metadata:
  name: farmer-service
  labels:
    app: farmer-service
spec:
  selector:
    app: farmer-service
  ports:
    - name: http
      port: 3000
      targetPort: 3000
